### ISSUE TITLE
Modifiers in the form of xdy+z?

### ISSUE THREAD

**Issue by featheredtoast** [bshef/hubot-dice-roller#1]
Any chance of supporting rolls with modifiers? xdy+z or xdy-z would be a helpful addition to a dice roller!

**Comment by brianshef** [comment]
You're absolutely right, this is an essential feature -- unfortunately I have little-to-no time for maintaining this project myself, currently... but I'm very open to pull requests!

**Comment by featheredtoast** [comment]
A fair point -- Meanwhile, I've found a different dice roller and am hacking on that for my needs. Thanks for the response!
